- Scripts/Flow/Video/Video - Denoise Non-Linear Means.js
- Scripts/Flow/Video/Video - Denoise nlmeans.js
Added a good denoise Filter- better than hqdn3d, faster than bm3d. Especially well suited for animation.
Improves compressibillity on average 5-10% - can go way higher on noisy source material.
> Create Video - Denoise nlmeans.js

- Scripts/Flow/Video/Video - Deblocking.js
Add a new video filter for removing block artefacts from a video stream. This can in some cases slightly improve compressability.
> Create Video - Deblocking.js

- Scripts/Flow/Video/Video - FPS greater than.js
Added some workarround for way to high fps
> Update Video - FPS greater than.js

- Scripts/Flow/Video/Inject HDR10+ metadata.js
Create script for injecting HDR10+ metadata into 10bit h265 videos
> Create Inject HDR10+ metadata.js

- Scripts/Flow/Video/Video - Inject HDR10+ metadata.js
Changed order of error processing to help catch initially unrecognised errors
> Update Video - Inject HDR10+ metadata.js

- Scripts/Flow/Video/Video - Devedse - RunAbAv1.js
Add option to use more options offered by AB-AV1, such as different encoders, maximum predicted size, bounds for CRF and more
> Add extra options to RunAbAv1

- Scripts/Flow/Video/Video - VMAF.js
Add vmaf script that will calculate the vmaf of the current video file compared to the original file.
> Add video - vmaf

- DockerMods/dovi_tool 2.1.1.sh
> dovi_tool dockermod

- Scripts/Shared/Radarr.js
- Scripts/Shared/Sonarr.js
> Shared scripts update for cross OS mapping compatibility

- Scripts/Shared/Radarr.js
- Scripts/Shared/Sonarr.js
> Constructor update

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Rename.js
- Scripts/Shared/Sonarr.js
> New scripts to detect and rename Series/Movies through Sonarr/Radarr

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Rename.js
- Scripts/Shared/Radarr.js
- Scripts/Shared/Sonarr.js
> Bug fix - Using folder name in path is ideal for cases of titles with special characters

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
- Scripts/Shared/Radarr.js
> Final update - this should ensure backwards compatibility and allow for search by path or file name

- Scripts/Shared/Sonarr.js
> Bug fix in getShowByPath

- Scripts/Flow/Video/Video - Blocklist sonarr or radarr.js
Change check to use Variables.folder.Orig.Name instead of Variables.folder.Name
> Update Video - Blocklist sonarr or radarr.js

- Scripts/Flow/Applications/Sonarr/Sonarr - Rename.js
> Updated logic to be more flexible in folder naming conventions

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Rename.js
- Scripts/Shared/Radarr.js
> Added query parameters support

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
> Properly increment radarr revision number

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
> Fix typo in description in Radarr Renamer

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Rename.js
> Added new output to differentiate an item not being found or rename not needed

- Scripts/Flow/Applications/Sonarr/Sonarr - Rename.js
- Scripts/Shared/Sonarr.js
> Add logic for sonarr to manually reimport file if it's not auto-detected, and other changes to logging

- Scripts/Shared/Sonarr.js
> Variable typo

- DockerMods/FFmpeg6.sh
> apt-key deprecated. Use GPG.

- Scripts/Flow/Video/Video - Delete Non-Original Language Audio.js
> Suggested changes for added flexibility

- Scripts/Flow/Video/Video - Delete Non-Original Language Audio.js
> Urgent helper bug fix

- DockerMods/dovi_tool 2.1.1.sh
> Update dovi_tool to 2.1.2

- Scripts/Flow/Applications/Lidarr/Lidarr - Manually trigger import.js
- Scripts/Flow/Applications/Radarr/Radarr - Manually trigger import.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Manually trigger import.js
> create uid's for sonarr/lidarr/radarr imports

- DockerMods/FFmpeg6.sh
Ensure gpg is called in batch mode and allow overriding previously downloaded keys
> Patch for ffmpeg6 dockermod with additional gpg flags

- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
This script uses mkvtoolsnix and dovi_tool too fix compatibility issues and cropping issues in Dolby Vision videos so that they will play on Sony Google TVs, iPhones, Android TV, fire stick  etc
> Dolby vision fixes

- DockerMods/btbn-ffmpeg7.sh
> BtbN FFMPEG 7.0.2 Git Master Static build dockermod

- Scripts/Flow/Applications/Radarr/Radarr - Movie Lookup.js
- Scripts/Flow/Applications/Sonarr/Sonarr - TV Show Lookup.js
I've created scripts for looking up in Radarr and Sonarr api and retrieve the media info and also set the OriginalLangauage variable
> Radarr and sonarr lookup scripts

- DockerMods/oneVPL.sh
So it seems that oneonevpl-tools installs some bits I didn't intend on and this is causing issues on later ARC cards
Please merge ASAP
> Change package list and checks to remove onevpl-tools

- DockerMods/FFmpeg7-BtbN.sh
Renamed script because you can't currently install it, I know you're working on all of these for a common tool path, so might not hurt to fix the code here
> Renamed ffmpeg 7 (btbn) so that you can install it

- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
Changed the paths so that they work on both windows and linux using `System.IO.Path.Combine(Flow.TempPath, "original.hevc")`
> Fix dovi widows

- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
Fixes for Mac and using with FileFlows file server
> File sever fixes for dovi_tool

- DockerMods/FFmpeg7-BtbN.sh
Minor improvements to logged output of FFmpeg7-BtbN.sh.
Now uses a more TTY-friendly progress indicator, and fixes a hard-coded string literal. 
> FFmpeg7-BtbN Log Shortening

- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
> Fix for people using remote mapping

- Scripts/Flow/File/File - Blocklist sonarr or radarr.js
> Update sonarr / radar blockscript to make them catch more

- DockerMods/FFmpeg7.sh
Based on the discord and my testing i think it’s time to just present ffmpeg7 as another option as it seems better especially for intel users
> Update and rename FFmpeg7-experimental.sh to FFmpeg7.sh

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Rename.js
> Update sonarr and radarr rename scripts to work with recent *arr updates and general logic fixes

- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
Change the extracting to mkvextract for mkv files
> Dolby Vision - script fix for mkv files

- Scripts/Flow/Applications/Radarr/Radarr - Trigger Manual Import.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Trigger Manual Import.js
Add check for import completion and remove trailing slash from URL
> Fix for Import *Arr scripts 

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Rename.js
Also removed trailing / in passed URI because that breaks things apaprently
> Fix bug in creating new file path relative to fileflows

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
> radarr renamer initialize variables properly

- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
This PR will fix an issue with mkvinfo not catching other dovi blocks in video track
> Fix for mkvinfo to recognize dovi block

- Scripts/Flow/Folder/Folder - Copy or Move Contents.js
Fixed typo in delete subdirectory variable.  Added logging.
> Update Folder - Copy or Move Contents.js

- Scripts/Flow/Applications/Radarr/Radarr - Rename.js
Fixed reference to incorrect variable in log statement
> Fixed variable ref in Radarr - Rename.js

- Scripts/Flow/Folder/Folder - Copy or Move Contents.js
> resolved merge conflict, changed directory check to create destination, not throw an error

- Scripts/Flow/Applications/Radarr/Radarr - Movie Lookup.js
- Scripts/Flow/Applications/Sonarr/Sonarr - TV Show Lookup.js
Added support for FileFlows thumbnails using SetThumbnail for movie/series lookup
> Add Sonarr/Radarr  support for FileFlows SetThumbnail

- Scripts/Flow/Video/Video - Filesize bigger than calculated.js
Initial version of a script that calculates a filesize by a given GB/hr variable for 4k,1080p,720p,SD and the input file's runtime. It then compares that size to the actual file size and returns if the input file is bigger or smaller than the calculated size.
> Create Video - Filesize bigger than calculated.js

- Scripts/Flow/Applications/Radarr/Radarr - Trigger Manual Import.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Trigger Manual Import.js
> Add timeout for sonarr/radarr scripts

- DockerMods/dovi_tool.sh
> upgrade dovi_tool to 2.2.0 and change some of the prints

- Scripts/Flow/Applications/Radarr/Radarr - Movie Lookup.js
- Scripts/Flow/Applications/Sonarr/Sonarr - TV Show Lookup.js
> fix param syntax

- DockerMods/dovi_tool.sh
Fix unneeded package that cause issues on install
> fix problematic package

- DockerMods/AutoCRF.sh
- Scripts/Flow/Video/Video - AutoCRF.js
The only VMAF script that ACTUALLY works!
> AutoCrf initial release

- Scripts/Flow/Applications/Lidarr/Lidarr - Manually trigger import.js
- Scripts/Flow/Applications/qBittorrent/qBittorrent - Renamer.js
- Scripts/Flow/Applications/qBittorrent/qBittorrent - Seeding check.js
- Scripts/Flow/File/File - Blocklist sonarr or radarr.js
- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
- Scripts/Flow/Video/Video - Dynamic range.js
Actually tested and all working this time :)
> Convert scripts to use Flow.Fail

- Scripts/Flow/Video/Video - Filesize bigger than calculated.js
Small improvements mostly for readability especially in log output.
> Minor improvements

- DockerMods/AutoCRF.sh
- Scripts/Flow/Video/Video - AutoCRF.js
Make AutoCRF work with "FFmpeg-BtbN with SVT-AV1-PSY and aom-psy101 added by Uranite" DockerMod
Increased maximum bitrate from 50 to 110 (this is the peak of a bluray)
Added h264 as a target
Fixed a few typos
> Community requested updates to AutoCRF

- Scripts/Flow/Video/Video - AutoCRF.js
> Add software mac and hardware nvidia support

- Scripts/Flow/Video/Video - Run ab-av1.js
Updated working on outputs of Run ab-av1 node as they were not clear
> Updated wording on outputs of Run ab-av1

- Scripts/Flow/Video/Video - AutoCRF.js
Set profile to main10 when dealing with DoVi fallback creation to help out amf and qsv
> AutoCRF: main10 / dovi fallback fixes

- Scripts/Flow/Video/Video - AutoCRF.js
> AutoCRF: fix QSV

- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
> DV: Fix mp4 source files

- DockerMods/dovi_tool.sh
Change dockermod from using static version to "latest" github release
> dovi_tool: use latest release

- Scripts/Flow/Video/Video - Run ab-av1.js
Update if statements which control options being added to the ab-av1 command to check if the value is not null/undefined due to issues caused by trying to trim some empty options
> Simplify option checks for ab-av1

- Scripts/Flow/Video/Video - AutoCRF.js
> AutoCRF typo

- Scripts/Flow/Video/Video - Run ab-av1.js
Update if statements for options to be a simple if statement as some options were not undefined in the function if empty
> Update Video - Run ab-av1.js

- Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
> Let the FileFlows GetVideoInfo tell us if the original has Dolby Vision

- Scripts/Flow/Applications/Radarr/Radarr - Trigger Manual Import.js
- Scripts/Flow/Applications/Sonarr/Sonarr - Trigger Manual Import.js
- Scripts/Shared/Radarr.js
- Scripts/Shared/Sonarr.js
Some small fixes for the Sonarr/Radarr for timeout for sending commands
> Fix Sonarr & Radarr timeout

- Scripts/Flow/Video/Video - AutoCRF.js
Sorry for about the PRs, i guess that's the download of being a popular script lol
> AutoCRF: remove optional from regex to fix libx265 issues

- Scripts/Flow/Applications/Radarr/Radarr - Movie Lookup.js
- Scripts/Flow/Applications/Sonarr/Sonarr - TV Show Lookup.js
- Scripts/Shared/Radarr.js
- Scripts/Shared/Sonarr.js
Improving Sonarr and Radarr lookup using *Arr Parsing and lookup in grabbed history
> Improving Radarr/Sonarr lookup

- Scripts/Flow/Video/Video - AutoCRF.js
> Update Video - AutoCRF.js

- Scripts/Flow/Video/Video - AutoCRF.js
> Added vaapi support, ability to read and use CustomParameters in tests, prefixed variables names, added thread options and hard coded qsv defaults

- Scripts/Flow/Video/Video - AutoCRF.js
> Remove AutoCRF prefix

- Scripts/Flow/Video/Video - Run ab-av1.js
> Add Score and CRF to Additional info recorder to ab-av1

- Scripts/Flow/Video/Video - AutoCRF.js
> Update the model not the vars

- Scripts/Flow/Utilities/Flow - Job Manager.js
Script which enables flow concurrency management.
> Add Flow - Job Manager

- IMDB-Lookup.js
This script will lookup IMDB ratings for Shows/Movies using mdblist api
> New script - IMDB Rating Lookup using MDBlist API
