Scripts/Flow/Video/Video - Denoise Non-Linear Means.js
"strength" was typed as "strenght" in the function parameters. This caused an error always because no strength could be provided to the video filter.
=> Fix typo  at "Denoise Non-Linear Means.js" file

Scripts/Flow/Video/Video - Audio bitrate per channel.js
Adds option to change bitrate of audio streams based on a number of channel basis to preserve current mix where possible. Works similarly to the -vbr setting of libfdk_aac and similar options of other codecs. Includes fallback option for when channels are not available in stream's metadata. Also includes optional buffer to keep existing audio/settings if it is within a range of the original track.
=> Add  Video - Audio bitrate per channel

Scripts/Flow/Video/Video - Devedse - InstallAbAv1.js, Scripts/Flow/Video/Video - Devedse - InstallFfmpegBtbN.js, Scripts/Flow/Video/Video - Devedse - RunAbAv1.js
I've added 3 scripts which all need to be ran in sequence to be able to install everything required for Ab-Av1.
Ab-Av1 is a tool that can determine what -crf value to use based on a desired VMAF value.
This won't need any dependencies as it obtains everything from the internet.
Some things to think about before mergin:
* I'm placing file in /app/Data/tools. This directory is hard coded as there is no variable available where FileFlows stores it's data. I would suggest exposing this to the scripts so I can create a tools folder under there and things will work. Without this I'm pretty sure other platforms won't work besides docker.
* All file downloading / reading / writing is done using bash commands. Currently this is the only way, but I think it would be better to expose functionality …
=> Added scripts to run AbAv1 + install the prerequisites

Scripts/Flow/Video/Video - VMAF.js
Fix issues with json file names such as with quotes due to the libvmaf filter stripping them.
=> VMAF: Fix issues with json file names

Scripts/Flow/Video/Video - Devedse - RunAbAv1.js
Add condition to error code so it returns 1 instead of failing when crf is not found
=> Update Video - Devedse - RunAbAv1.js

Scripts/Flow/Video/Video - Dynamic range.js
Detects the dynamic range of a video e.g. SDR/HDR/HDR+DoVi/Dovi
Unsure how useful this is but I use it a lot in combination with my blocklist script as I never want Dolby Vision only videos
=> Detects the dynamic range type

DockerMods/IntelVPL.sh
You may remember this script... haha.. I did remove a bunch of things though... 
So it seems in May intel decided to replace the graphics drivers in linux with something called the OneVPL drivers, instead of the standard Media SDK driver. On ubuntu this is called `intel-media-va-driver-non-free` 
It seems some dists of arch and probably ubuntu in the far future are using that. To get QSV working you need to install a few things in the container so that ffmpeg knows to use the new api.
I have tested this and I get about 11fps more so it works... it also claims to solves some GPU hang issues, basically if you have a new intel graphics card you're also gonna want to use this because they've decided not to update the old driver :(
[X] I agree that by opening a pull requests I am handing over …
=> Add intel VPL drivers

DockerMods/FFmpeg7-experimental.sh
I’ve called this experimental because it’s not the default. However it’s had its first official jellyfin build
https://github.com/jellyfin/jellyfin-ffmpeg/releases
I can confirm that this update version does work and includes the DoVi fixes
=> New dockermod for ffmpeg7

Scripts/Flow/Video/Video - Devedse - RunAbAv1.js
Existing logic for detecting final VMAF value is incorrect - it is picking up the first VMAF calculated, not the final value.   Most likely due to changes in the logging output of ab-av1.   This change picks up the final calculated VMAF using a more precise match pattern.
=> Update Video - Devedse - RunAbAv1.js; fix regex to pickup final CRF value

Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
This changes the detection logic by looking at the original video rather than using the Variables which will be from the generated video. 
Using jellyfin builds this is not a problem but as BTN can't copy over the DoVi RPU itself I needed to change the logic.
=> [Dovi fix] Change detection logic

Scripts/Flow/Video/Video - Devedse - RunAbAv1.js
Fix regex statement to work with updated output of abav1
=> Fix RunAbAv1 found crf match

Scripts/Flow/Folder/Folder - Copy or Move Contents.js
Add new script for an improved copy/move folder script that is compatible with moving contents of folders when a folder contains more more than 1 work-unit to be processed by flows separately.
=> New Script: Folder - Copy or Move Contents.js

Scripts/Flow/Applications/Radarr/Radarr - Get Original Language.js, Scripts/Flow/Applications/Sonarr/Sonarr - Get Original Language.js
The current script lacks an URL and an API key, so there is no way it can get anything out of Radarr
=> Fix Radarr - Get Original Language.js -- missing URL and API key

Scripts/Flow/Applications/qBittorrent/qBittorrent - Renamer.js, Scripts/Flow/Applications/qBittorrent/qBittorrent - Seeding check.js
This introduces two scripts...
Renamer - this will change the file name inside qbt, designed to be run after the move so that if the file extension changes radarr/sonarr can still import the file, this rarely is an issue for *darr but seems to be an issue with single file torrents more than anything
Seeding check - this will check inside qbt to see if the file is seeding, so you can retry the file later
Both of these scripts have been in use for a couple of weeks now and have had no issues. 
=> Added qbittorent scripts

DockerMods/FFmpeg-BtbN with SVT-AV1-PSY and aom-psy101 added by Uranite.sh
The PSY variant of FFmpeg includes SVT-AV1-PSY and aom-psy101. These are CPU encoders for AV1 that focus on visual fidelity.
From what I can see is that the Uranite github fork automatically updates every time BtbN updates and also includes the latest -psy variants.
=> Added FFmpeg-BtbN with PSY

Scripts/Shared/Radarr.js, Scripts/Shared/Sonarr.js
Add timeout param for shared Sonarr/Radarr scripts in `waitForCompletion` method
=> Add timeout param for shared Sonarr/Radarr scripts

Scripts/Flow/Video/Video - Has 5.1 Audio.js
Added a tolerance window so that the check will still resolve true when channel counts report as long decimals due to JavaScript floating point issues.  
E.G. "Audio channel found: 5.09999990463256" =/= 5.1  //Returns Output 2
=> Update Video - Has 5.1 Audio.js Added Tolerance

Scripts/Flow/Video/Video - AutoCRF.js
Tested with the following Variables added to FF
SVT
lookahead=64:hierarchical-levels=4:irefresh-type=1:scm=0:aq-mode=2:psy-rd=3:spy-rd=1:enable-variance-boost=1:variance-boost-strength=2:variance-octile=6:qp-scale-compress-strength=1:noise-norm-strength=3:sharpness=1:tf-strength=2:film-grain=8
KeyInt
240
TargetCodec
libsvtav1
Preset
8
=> Added ability to use software av1 svt

Scripts/Flow/Video/Video - Dolby Vision - Fix crop and compatibility.js
=> escape name under linux because we unwrap the arguments later

Scripts/Flow/Applications/Sonarr/Sonarr - Refresh.js
Misconfigured usage of sonarr.waitForCompletion caused it to fail immediately with the timeout error. The sonarr class was being passed on the timeout value parameter.
=> Misconfigured usage of sonarr.waitForCompletion in the "Sonarr - Refresh.js" script

Scripts/Flow/Video/Video - Run ab-av1.js
Checked if there is a message from ab-av1 before printing to ILog.
Also ensures that returnValue.message is a string via a template as the ILog appears to use a trim function that does not work for classes without a trim function
=> Fix printing of return message - Run abav1

Scripts/Flow/Video/Video - Run ab-av1.js
Add check to ensure that the table fields for the ab-av1 messages have a value before attempting to trim them
=> Add check before trimming extracted score info

Scripts/Flow/Applications/Radarr/Radarr - Movie Lookup.js, Scripts/Flow/Applications/Radarr/Radarr - Trigger Manual Import.js, Scripts/Flow/Applications/Sonarr/Sonarr - TV Show Lookup.js, Scripts/Flow/Applications/Sonarr/Sonarr - Trigger Manual Import.js
Big improvement for Sonarr/Radarr Import media, using 2 flows when that will use `Manual Import` as in UI or `Download Scan` command.
To work with Manual Import, the users will need to add Radarr/Sonarr lookup scripts or it will use the `Download Scan` by default.
=> Adding Manual Import along with Download Scan for better imports

Scripts/Flow/Applications/Sonarr/Sonarr - TV Show Lookup (Library).js
An alternative to the other script, which now only works against queue or grab / download history, failing the lookup for series having been added and downloaded a long time before analysing them.
This instead searches against the library.
=> Create new Sonarr - TV Show Lookup script for search against sonarr library

Scripts/Flow/Video/Video - Run ab-av1.js
Add valid directory for ab-av1 scoring cache to be flow's temp directory
=> Run ab-av1 - add scoring cache directory
